#!/usr/bin/env python3
"""consolidate.py — turn raw signals into durable learnings. Runs on Stop (per turn-end).

This is the refine stage flat-text systems skip:
  - PATCH: a recurring signal bumps one learning's seen_count, not a new line.
  - GUARDRAIL: environment/transient noise is dropped (store.is_noise).
  - PROMOTE: a learning seen >= EVOLVE_PROMOTE_AT becomes a real .claude/skills/SKILL.md
             so Claude Code auto-loads it next session.
  - CURATE: stale/old learnings transition state (excluded from injection).

Pure stdlib, no LLM, model-agnostic. Optional LLM polish if EVOLVE_LLM=1 (uses
`claude -p`, i.e. whatever model the user already runs).
Idempotent and silent: always exits 0.
"""
import json
import os
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import store  # noqa: E402

SKILLS_DIR = lambda: store.project_root() / ".claude" / "skills"  # noqa: E731


# Error codes (rustc E0382, tsc TS2345, mypy/eslint, Go vet, etc.) are the stable
# identity of a recurring failure — far better than the volatile message text.
_ERRCODE = re.compile(r"error\[([A-Za-z]+\d+)\]|\b([A-Z]{1,5}\d{3,5})\b|\b(E\d{3,4})\b")


def _err_code(text: str) -> str:
    m = _ERRCODE.search(text or "")
    if not m:
        return ""
    return next(g for g in m.groups() if g)


def _title_from(sig: dict):
    """Return (type, title, body, key). key drives patch-not-append dedup."""
    t = sig.get("type")
    if t == "build_failure":
        err = sig.get("error", "")
        first = (err.strip().splitlines() or [""])[0][:100]
        code = _err_code(err)
        key = f"build:{code}" if code else "build:" + store.normalize(first)
        return ("build_failure",
                f"Build error: {first}",
                f"Command: `{sig.get('command','')}`\nError:\n{err[:1500]}", key)
    if t == "fix_found":
        code = _err_code(sig.get("error", ""))
        key = f"fix:{code}" if code else "fix:" + store.normalize(sig.get("error", ""))
        return ("fix",
                f"Fix: {sig.get('failed_command','')[:60]} -> {sig.get('fix_command','')[:60]}",
                f"When `{sig.get('failed_command','')}` fails"
                f" (error: {sig.get('error','')[:200]}),\n"
                f"the fix that worked was: `{sig.get('fix_command','')}`", key)
    if t == "correction":
        txt = sig.get("text", "")
        return ("correction",
                f"User correction: {txt[:60]}",
                f"User pushed back with: \"{txt[:400]}\". "
                f"Recall the surrounding context to avoid repeating the mistake.",
                "correction:" + store.normalize(txt))
    return ("note", sig.get("text", "")[:60], json.dumps(sig)[:500], "")


def _llm_polish(rec: dict) -> None:
    """Optional: tighten title/body via the user's own model. Off by default."""
    if os.environ.get("EVOLVE_LLM") != "1":
        return
    prompt = (
        "Rewrite this engineering learning as a crisp, reusable rule (<=2 sentences). "
        "Output ONLY the rule text.\n\n"
        f"Title: {rec['title']}\nBody: {rec['body']}"
    )
    try:
        r = subprocess.run(["claude", "-p", prompt, "--output-format", "text"],
                           capture_output=True, text=True, timeout=60)
        out = (r.stdout or "").strip()
        if out and len(out) < 600:
            rec["body"] = out
    except Exception:
        pass


def _promote(rec: dict) -> None:
    """Write a learning as an auto-loadable SKILL.md once it's proven (seen >= threshold)."""
    if rec.get("promoted") or rec.get("seen_count", 1) < store.PROMOTE_AT:
        return
    if rec.get("type") not in ("fix", "correction", "build_failure"):
        return
    slug = "evolve-" + re.sub(r"[^a-z0-9]+", "-", rec["title"].lower()).strip("-")[:40]
    sdir = SKILLS_DIR() / slug
    sdir.mkdir(parents=True, exist_ok=True)
    desc = rec["title"].replace("\n", " ")[:200]
    md = (
        f"---\n"
        f"name: {slug}\n"
        f"description: >-\n  Learned rule ({rec['type']}, seen {rec['seen_count']}x): {desc}\n"
        f"metadata:\n  source: claude-evolve\n  seen_count: {rec['seen_count']}\n"
        f"---\n\n"
        f"# {rec['title']}\n\n{rec['body']}\n\n"
        f"_Auto-generated by claude-evolve after recurring {rec['seen_count']}x. "
        f"First seen {rec['first_seen']}._\n"
    )
    (sdir / "SKILL.md").write_text(md)
    rec["promoted"] = True
    rec["skill"] = slug


def main() -> None:
    signals = store.read_signals()
    if not signals:
        sys.exit(0)
    data = store.load_learnings()
    promoted_now = []
    for sig in signals:
        typ, title, body, key = _title_from(sig)
        if store.is_noise(title + " " + body):
            continue
        rec = store.upsert(data, typ, title, body, key=key or None)
        _llm_polish(rec)
        was = rec.get("promoted")
        _promote(rec)
        if rec.get("promoted") and not was:
            promoted_now.append(rec["skill"])
    store.curate(data)
    store.save_learnings(data)
    store.clear_signals()

    # Report into the transcript (Stop hook stdout is shown to the user).
    n = sum(1 for r in data.values() if r.get("state") == "active")
    if promoted_now:
        print(f"[evolve] learned {len(signals)} signal(s); "
              f"promoted to skills: {', '.join(promoted_now)} | {n} active learnings")
    sys.exit(0)


if __name__ == "__main__":
    main()
