#!/usr/bin/env python3
"""export_md.py — write .claude/evolve/LEARNINGS.md, the high-reliability resurfacing
channel. Auto-skills only fire when their description matches the task; SessionStart
injection always lands but is capped. A markdown file the user @imports from CLAUDE.md is
read on EVERY turn with top priority — the surest way for Claude to actually apply lessons.

Regenerated on every consolidate. The user wires it once:  add  @.claude/evolve/LEARNINGS.md
to the project's CLAUDE.md. Usage (standalone): python3 export_md.py
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import store  # noqa: E402

MAX_ITEMS = int(__import__("os").environ.get("EVOLVE_MD_MAX", "25"))


def build(data: dict) -> str:
    active = [r for r in data.values() if r.get("state") == "active"]
    active.sort(key=store.confidence, reverse=True)
    active = active[:MAX_ITEMS]
    if not active:
        return ""
    groups = {"correction": [], "build_failure": [], "fix": []}
    for r in active:
        groups.get(r.get("type"), groups["fix"]).append(r)

    out = [
        "# Project learnings (auto-generated by claude-evolve)",
        "",
        "Apply these accumulated lessons; do not repeat past mistakes. This file is "
        "regenerated automatically — edit lessons via `/claude-evolve:review`, not here.",
        "",
    ]
    labels = [("correction", "Preferences & corrections"),
              ("build_failure", "Recurring build/test failures"),
              ("fix", "Known fixes")]
    for key, heading in labels:
        rows = groups.get(key) or []
        if not rows:
            continue
        out.append(f"## {heading}")
        for r in rows:
            seen = r.get("seen_count", 1)
            body = store.sanitize(r.get("body", "")).replace("\n", " ").strip()
            title = store.sanitize(r.get("title", "")).strip()
            line = f"- **(seen {seen}x)** {title}"
            if body and body[:120] not in title:
                line += f" — {body[:160]}"
            out.append(line)
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def write(data: dict) -> str:
    md = build(data)
    p = store.store_dir() / "LEARNINGS.md"
    if not md:
        return ""
    store.ensure_store()
    p.write_text(md)
    return str(p)


def main() -> None:
    out = write(store.load_learnings())
    print(f"wrote {out}" if out else "no active learnings to export")


if __name__ == "__main__":
    main()
